[build]

[env]
  NODE_ENV = "production"
  DATABASE_URL = "file:./dev.db"
  JWT_SECRET = "meatmaster_jwt_secret_prod_fly_2026"
  JWT_REFRESH_SECRET = "meatmaster_refresh_secret_prod_fly_2026"
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = "shared-cpu-1x"
